version: 1.0.{build}
environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 7
build_script:
- ps: >-
    Install-Product node $env:nodejs_version
    npm install --loglevel=error
test_script:
- cmd: >-
    npm run build